name: farm_genius
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  
  google_fonts: ^6.2.1
  intl: ^0.20.2
  
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/farm_logo.png
    - assets/bg.jpg
    - assets/image.png
    - assets/asset1.png

