name: farm_genius
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  pie_chart: ^5.4.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.0.0
  provider: ^6.1.4
  http: ^1.0.0
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.5.0
  smooth_page_indicator: ^1.1.0
  firebase_auth: ^5.5.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/farm_logo.png
    - assets/bg.jpg
    - assets/image.png
    - assets/asset1.png
    - assets/corn.jpeg
    - assets/wheat.jpg
    - assets/soybean.jpg
    - assets/rice.webp
